name: Create Release and Update Repository

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    uses: Catphinaud/DalamudPlugins/.github/workflows/reusable_create_release.yml@main
    with:
      internal_name: StatusLinker
      solution_name: StatusLinker
      build_configuration: Release
      personal_plugin_repo: Catphinaud/DalamudPlugins
      personal_plugin_repo_branch: main
    secrets: inherit
